language: clojure
matrix:
  include:
    - jdk: openjdk12
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
notifications:
  slack:
    secure: hzeR0K7BTxHUp8yNYqF2cgvUII/ZQA61UyVDfiLzxTT+4NHK+sUirnPyyk+DHxxjJxQmzK7PqjUzlJ0NiYomfFOCa9gvj5dTgKDEJ6sAjPJ7BNHuyXsYV4jT2h2MysIX5Z4TJbZFdX/MfszTHLGCzXZUJ7/Ubwo9oypnDy0ZEdcxvhqII21KJ7WJHSvteTj8FvKIHY26myme8JM46ktnIEletveBbGfuGbxbp76I2h0wXcXL77h5FstTB/TeMTQtH0VFKqjHG9OnmkrSB2bNtzYjWYDnqD1tXHJYuzB1CDtDsA8N/JG4Wq98He21nkoqhyfUCVg6BkfGHBBnUrIRlT28pSBHjRjGnAI3LcO8uo0mW0R9xUJGnCU3fPz+Lgo4d0p8MpWjb56PgT5TG4QmNO+ZXXX5tCUQLJtogcpUZis1RXKMfSdmyxWuNlYn0e5HpmFKVRJMECM06Tz6AIRS1IR0CDiYkqfPygXfgjdMwlzkm1nWou6SliYWmXD1myXERRk4Fsze91xH9HmYwpMdR4zZ2trRDU/TZZMhvanYLYhg0es4h8HRMn1dOOOM8oyRI2KbXHKFrICE3M8GAjOyFztznl2Bq0FsOZrZNmJG+FBBXK35I02it8pTKmYgEjSNagvEFKyZqpFeuMnX8EGAFKxr6s3pAzs3ky3zX7ho8Wk=
